version: "3.9"
services:
  frontend:
    container_name: nginx-frontend-app
    image: frontend
    build:
      context: ./client/
      dockerfile: Dockerfile-local
    env_file:
      - .env
    ports:
      - 80:80
      - 443:443

  backend:
    container_name: node-app
    image: backend
    build:
      context: ./server/
      dockerfile: Dockerfile
    env_file:
      - .env

